#----------------------------------------------------------------------------------------------------------------------
# CHART PARAMETERS TO AUGMENT values.yaml WITH SECRET
# This file declares additional input parameters to set the SERVER_TEXT environment variable in the application
# container from a Secret.
#
# This values file is intended to be used with the values.yaml file:
# helm install k8s-service -f values.yaml -f ./extensions/secret_values.yaml
#
# See the README for more details
#----------------------------------------------------------------------------------------------------------------------

# secrets is a map that specifies which Secret resources should be injected into the application container. There
# are two ways that a Secret can be injected:
# - as an environment variable
# - as a file on the file system
# In this example, we inject the sample-sinatra-app-server-text Secret defined in kubernetes/secret.yaml to set
# the SERVER_TEXT environment variable on the application container.
secrets:
  sample-sinatra-app-server-text:
    as: environment
    items:
      server_text:
        envVarName: SERVER_TEXT
